### ISSUE TITLE
[RFC]: merge flags of state registrar

### ISSUE THREAD

**Issue by rezamahdi** [erfan-khadem/rpi8080#1]
It seems there is no need to declare flags as bit fields.
Just use an unit8 and preprocessor macros
and logical operations.

**Comment by erfan-khadem** [comment]
Hi Reza.

I also think that there are a few low hanging fruits in the implementation. But I also want the source code to be highly readable and maintainable, with as little "magic" as possible. Right now, my main focus is providing good tooling and documentation without breaking any of the existing functionality.

Please keep in mind that our emulation core is taken from another project with a good reputation (you may find the link to the original repository in readme.md) and right now it is not a priority to change their well tested code.
